# Troubleshooting Documentation Schema
# This schema MUST be validated before writing any troubleshooting doc

required_fields:
  plugin:
    type: string
    description: "Plugin name (e.g., 'GainKnob', 'TapeAge') or 'JUCE' for generic issues"
    examples:
      - "GainKnob"
      - "TapeAge"
      - "JUCE"  # For generic JUCE issues not specific to a plugin

  date:
    type: string
    pattern: '^\d{4}-\d{2}-\d{2}$'
    description: "Date when this problem was solved (YYYY-MM-DD)"

  problem_type:
    type: enum
    values:
      - build_error          # CMake, linker, compiler errors
      - runtime_error        # Crashes, exceptions during execution
      - api_misuse           # Incorrect JUCE API usage
      - validation_failure   # pluginval crashes/errors
      - ui_layout            # Visual/layout issues
      - dsp_issue            # Audio processing problems
      - state_management     # APVTS, parameter saving/loading
      - performance          # CPU spikes, memory issues
      - thread_violation     # Real-time safety violations
    description: "Primary category of the problem"

  component:
    type: enum
    values:
      - cmake                # Build system
      - juce_processor       # AudioProcessor/PluginProcessor
      - juce_editor          # AudioProcessorEditor/PluginEditor
      - juce_dsp             # juce::dsp namespace (Compressor, Delay, etc.)
      - juce_gui_basics      # Slider, Button, Label, FlexBox, etc.
      - juce_audio_utils     # AudioDeviceManager, etc.
      - apvts                # AudioProcessorValueTreeState
      - pluginval            # Validation tool
      - xcode                # Xcode-specific issues
      - system               # macOS/system-level issues
      - webview              # JUCE WebBrowserComponent
    description: "JUCE module or system component involved"

  symptoms:
    type: array[string]
    min_items: 1
    max_items: 5
    description: "Observable symptoms (error messages, visual issues, crashes)"
    examples:
      - "Linker error: undefined symbols for juce::dsp::Compressor"
      - "Rotary sliders overlap in UI"
      - "Plugin crashes when loading in Ableton"

  root_cause:
    type: enum
    values:
      - missing_framework    # Framework not linked
      - missing_module       # JUCE module not linked in CMakeLists
      - wrong_api            # Using deprecated/incorrect API
      - thread_violation     # Real-time unsafe operation
      - missing_constraint   # FlexBox missing size constraints
      - state_sync           # Parameter state not syncing
      - memory_issue         # Leak, double-free, etc.
      - config_error         # CMake or build config wrong
      - version_incompatibility  # JUCE version mismatch
      - logic_error          # Algorithm/logic bug
      - event_timing         # Event sequencing or timing issue
      - url_protocol         # URL protocol or format issue
    description: "Fundamental cause of the problem"

  resolution_type:
    type: enum
    values:
      - code_fix             # Fixed by changing source code
      - config_change        # Fixed by changing CMakeLists/build config
      - environment_setup    # Fixed by installing/configuring system
      - api_migration        # Fixed by migrating to new API
    description: "Type of fix applied"

  severity:
    type: enum
    values:
      - critical             # Blocks development (build fails, plugin crashes)
      - moderate             # Impairs functionality (UI broken, DSP incorrect)
      - minor                # Cosmetic or edge case
    description: "Impact severity"

optional_fields:
  juce_version:
    type: string
    pattern: '^\d+\.\d+\.\d+$'
    description: "JUCE version where this was encountered (e.g., '8.0.4')"

  related_components:
    type: array[string]
    description: "Other components that interact with this issue"

  tags:
    type: array[string]
    max_items: 8
    description: "Searchable keywords (lowercase, hyphen-separated)"
    examples:
      - "flexbox"
      - "real-time"
      - "linker"

validation_rules:
  - "plugin must be a valid plugin name or 'JUCE'"
  - "date must be in YYYY-MM-DD format"
  - "problem_type must match one of the enum values"
  - "component must match one of the enum values"
  - "symptoms must be specific and observable (not vague)"
  - "root_cause must be the ACTUAL cause, not a symptom"
  - "resolution_type must match one of the enum values"
  - "severity must match one of the enum values"
  - "tags should be lowercase, hyphen-separated"

# Example valid front matter:
# ---
# plugin: GainKnob
# date: 2025-11-10
# problem_type: ui_layout
# component: juce_gui_basics
# symptoms:
#   - Rotary sliders overlap in UI
#   - All sliders render at top-left corner
# root_cause: missing_constraint
# juce_version: 8.0.9
# resolution_type: code_fix
# severity: moderate
# tags: [flexbox, layout, slider, sizing]
# ---
